# Generated by Django 5.1.7 on 2025-03-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock_quantity",
            new_name="stock",
        ),
    ]
