# Generated by Django 5.1.7 on 2025-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0003_rename_stock_quantity_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
