# Generated by Django 5.1.7 on 2025-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0004_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.AlterField(
            model_name="purchase",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
