# Generated by Django 5.1.7 on 2025-03-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0005_remove_product_slug_alter_purchase_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="purchases",
            field=models.ManyToManyField(
                related_name="billing_purchases", to="template.purchase"
            ),
        ),
    ]
