# Generated by Django 5.1.7 on 2025-03-27 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0007_purchase_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="purchased_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
