# Generated by Django 5.1.7 on 2025-03-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0008_purchase_purchased_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="product",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="template.product",
            ),
        ),
    ]
