# Generated by Django 5.1.7 on 2025-03-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0009_purchase_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
