# Generated by Django 5.1.7 on 2025-03-27 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "template",
            "0012_alter_addtocart_added_date_alter_addtocart_quantity_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="total",
            new_name="total_amount",
        ),
        migrations.AlterField(
            model_name="addtocart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
