# Generated by Django 5.1.7 on 2025-03-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0013_rename_total_billing_total_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="total_amount",
            new_name="total",
        ),
    ]
